import Head from "next/head";
import Product from "../components/productThumbnail/product";
import productsLayout from "../styles/ProductsLayout.module.css";

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Da Shop</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Products:</h1>
      <div className={productsLayout.products}>
        {data.map(({ id, image, title, rating }) => (
          <Product
            key={id}
            image={image}
            title={title}
            rating={rating}
            id={id.toString()}
          />
        ))}
      </div>
    </div>
  );
}

export async function getStaticProps(context) {
  const res = await fetch("https://fakestoreapi.com/products/");
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: { data },
  };
}
